# German Words

matches:

  - trigger: ":o"
    replace: "ö"
  - trigger: ":O"
    replace: "Ö"
  - trigger: ":a"
    replace: "ä"
  - trigger: ":A"
    replace: "Ä"
  - trigger: ":u"
    replace: "ü"
  - trigger: ":U"
    replace: "Ü"
  - trigger: ":Good morning"
    replace: "Guten Morgen"
  - trigger: ":How are you?"
    replace: "Wie geht es dir?"
  - trigger: ":Thank you"
    replace: "Dankeschön"
  - trigger: ":Bye"
    replace: "Tschüss"
  - trigger: ":Hi"
    replace: "Hallo"
  - trigger: ":See you next time"
    replace: "Aufwiedersehen"
  - trigger: ":the1"
    replace: "Der"
  - trigger: ":the2"
    replace: "Die"
  - trigger: ":the3"
    replace: "Das"
  - trigger: ":yes"
    replace: "Ja"
  - trigger: ":no"
    replace: "Nein"
  - trigger: ":but"
    replace: "Aber"
  - trigger: ":only"
    replace: "Nur"
  - trigger: ":on"
    replace: "An"
  - trigger: ":close"
    replace: "Zu"
  - trigger: ":from"
    replace: "Von"
  - trigger: ":S"
    replace: "ß"
  - trigger: ":apple"
    replace: "Apfel"
  - trigger: ":house"
    replace: "Haus"
  - trigger: ":dog"
    replace: "Hund"
  - trigger: ":book"
    replace: "Buch"
  - trigger: ":computer"
    replace: "Computer"